name: Jailer
version: ${project.version}
main: jailer.jailer.Jailer
api-version: 1.19
authors: [ shwendel, MrEnx0 ]
depend: [ Citizens ]
description: Jailer
commands:
  items:
    description: Open an inventory of all Jailer Items