name: Seafront
version: ${project.version}
main: seafront.seafront.Seafront
api-version: 1.19
authors: [ shwendel, MrEnx0 ]
depend: [ Citizens ]
description: Core for the Seafront rpg server
commands:
  items:
    description: Open an inventory of all Seafront Items
  mine:
    permission: seafront.admin.mine
    description: mine command for admins